#!/bin/bash

setup_central_user() {
  if [[ $(confirm "Do you want to create a new central sudo user? This is recommended if only root is available.") = true ]]; then
    echo "Please type in a name for the new admin user: "
    read adminusr
    {
      sudo adduser --disabled-password --gecos "" $adminusr
      sudo usermod -aG sudo $adminusr
    }

    read -s -p "Fill in a password for the new user: " adminpwd
    sudo usermod --password $adminpwd $adminusr
    unset adminpwd # for security
    cd $cwd # back to the roots
    log "Created user $adminusr with sudo role" INFO
  fi
}

setup_crontab() {
  # Limit crontab to new root user
  append_to_file "$adminusr" /etc/cron.d/cron.allow
  log "Added user to allowed crontab users: $adminusr." INFO
}

command_setup() {
  while [[ $# -gt -1 ]]; do
  case $1 in
    "")
      setup_central_user
      setup_crontab
      install_ufw
      install_ssh
      install_fail2ban
      if [[ $(confirm "Install SELinux for increased security? This will require advanced configuration") = true ]]; then
        install_selinux
      fi
      log "Your system has been secured with some basic practises. You may go through one or many of these steps again by using ced init" INFO
      exit 0
      ;;
    "user")
      setup_central_user
      shift
      ;;
    "cron")
      setup_crontab
      shift
      ;;
    *)
      command_init_help
      ;;
    esac
  done
}
